Repository redpanda-data/documentation, pull requests merged in 2023-08, with the labels that each got.

#1672 Add `Supported versions` field for properties introduced in 23.x
  docs/reference/cluster-properties.mdx
  docs/reference/tunable-properties.mdx
  versioned_docs/version-22.3/reference/cluster-properties.mdx
  versioned_docs/version-23.1/reference/tunable-properties.mdx
Labels: backport

#1800 docs: #1362 add incompatible changes to upgrade page
  docs/manage/cluster-maintenance/index.mdx
  docs/manage/cluster-maintenance/rolling-upgrade.mdx
  docs/manage/kubernetes/rolling-upgrade.mdx
  docs/upgrade/migrate/index.mdx
  sidebars.js
Labels: backport

#1791 docs: #1769 what's new page
  docs/develop/config-topics.mdx
  docs/get-started/architecture.mdx
  docs/get-started/index.mdx
  docs/get-started/whats-new.mdx
  docs/manage/cluster-maintenance/cluster-balancing.mdx
  docs/manage/cluster-maintenance/disk-utilization.mdx
  docs/manage/security/console/tls-termination.mdx
  docs/manage/shared/tiered-storage/_archived-metadata.mdx
  docs/manage/shared/tiered-storage/_caching.mdx
  docs/manage/shared/tiered-storage/_cloud-storage-housekeeping.mdx
  docs/manage/shared/tiered-storage/_space-usage.mdx
  sidebars.js
Labels: backport

#1821 Fix redpanda_cluster_brokers description
  docs/reference/public-metrics-reference.mdx
  versioned_docs/version-22.3/reference/public-metrics-reference.mdx
  versioned_docs/version-23.1/reference/public-metrics-reference.mdx
Labels: backport

#1831 Add Configure Offset Retention
  docs/manage/cluster-maintenance/disk-utilization.mdx
Labels: backport

#1828 Add restart-required admonition to node properties reference
  docs/reference/node-properties.mdx
  versioned_docs/version-22.1/reference/node-properties.mdx
  versioned_docs/version-22.2/reference/node-properties.mdx
  versioned_docs/version-22.3/reference/node-properties.mdx
  versioned_docs/version-23.1/reference/node-properties.mdx
Labels: backport

#1823 Update description for retention.local.target.bytes
  docs/reference/topic-properties.mdx
  versioned_docs/version-23.1/reference/topic-properties.mdx
Labels: backport

#1826 Add tip for multiple principals in comma-separated list
  docs/manage/security/authorization.mdx
  docs/shared/_rpk-acl-tip.mdx
  tools/rpk/gen/rpk-acl.mdx
  versioned_docs/version-22.2/reference/rpk/rpk-acl/rpk-acl.mdx
  versioned_docs/version-22.2/security/authorization.mdx
  versioned_docs/version-22.2/shared/_rpk-acl-tip.mdx
  versioned_docs/version-22.3/manage/security/authorization.mdx
  versioned_docs/version-22.3/reference/rpk/rpk-acl/rpk-acl.mdx
  versioned_docs/version-22.3/shared/_rpk-acl-tip.mdx
  versioned_docs/version-23.1/manage/security/authorization.mdx
  versioned_docs/version-23.1/reference/rpk/rpk-acl/rpk-acl.mdx
  versioned_docs/version-23.1/shared/_rpk-acl-tip.mdx
Labels: backport

#1838 Docs: added documentation about connecting Self-hosted Connectors with Redpanda Cloud cluster
  docs/deploy/deployment-option/self-hosted/docker-image.mdx
Labels: backport

#1795 Redpanda Cloud-platform compatibility
  docs/deploy/deployment-option/cloud/cloud-overview.mdx
Labels: backport

#1827 Use base-uri variable for curl requests
  docs/develop/http-proxy.mdx
Labels: backport

#1829 Update description of redpanda_kafka_max_offset
  docs/reference/public-metrics-reference.mdx
Labels: backport

#1806 docs: Deprecated Operator migration guide
  docs/deploy/deployment-option/self-hosted/kubernetes/kubernetes-deploy.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/kubernetes-production-deployment.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/local-guide.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/shared/guides/_deploy-redpanda.mdx
  docs/upgrade/deprecated/cluster-resource.mdx
  docs/upgrade/migrate/index.mdx
  docs/upgrade/migrate/kubernetes/helm-to-operator.mdx
  docs/upgrade/migrate/kubernetes/operator.mdx
  docs/upgrade/shared/install-migration-cli/_install-migration-cli-linux.mdx
  docs/upgrade/shared/install-migration-cli/_install-migration-cli-macos.mdx
  docs/upgrade/shared/install-migration-cli/_migration-cli-version.mdx
  sidebars.js
Labels: backport

#1884 remove wasm backport 22.3
  modules/ROOT/nav.adoc
  modules/labs/pages/data-transform.adoc
  modules/labs/pages/index.adoc
  modules/labs/pages/install-preview.adoc
  modules/manage/partials/tiered-storage.adoc
  modules/reference/pages/cluster-properties.adoc
  modules/reference/pages/rpk/rpk-wasm/rpk-wasm-deploy.adoc
  modules/reference/pages/rpk/rpk-wasm/rpk-wasm-generate.adoc
  modules/reference/pages/rpk/rpk-wasm/rpk-wasm-remove.adoc
  modules/reference/pages/rpk/rpk-wasm/rpk-wasm.adoc
  modules/reference/pages/tunable-properties.adoc
Labels: backport v/22.2, backport v/22.1, backport v/21.11

#1892 backport #1822
  modules/reference/pages/cluster-properties.adoc
Labels: backport to v/22.3 v/23.1
