Repository redpanda-data/documentation, pull requests merged in 2023-02, with the labels that each got.

#1059 Information on what to monitor for Redpanda
  docs/manage/monitoring.mdx
  docs/reference/cluster-properties.mdx
  docs/reference/index.mdx
  docs/reference/internal-metrics-reference.mdx
  docs/reference/internal-metrics.mdx
  docs/reference/monitor-metrics.mdx
  docs/reference/public-metrics-reference.mdx
  docs/shared/_metrics-usage-tip.mdx
  sidebars.js
  versioned_docs/version-22.2/cluster-administration/monitoring.mdx
Labels: P2

#1141 docs: Update configuration for rack awareness
  docs/manage/kubernetes/kubernetes-rack-awareness.mdx
Labels: kubernetes

#1112 docs: Add EBS CSI add-on to Operator installation tutorial
  docs/reference/redpanda-operator/kubernetes-qs-cloud.mdx
Labels: kubernetes, Operator

#1174 engine: add beta path
  docusaurus.config.js
Labels: website engine, usability improvement, P3

#1125 docs: Add a guide for deploying Redpanda in AKS
  docs/deploy/deployment-option/index.mdx
  docs/deploy/deployment-option/self-hosted/index.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/aks-guide.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/eks-guide.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/get-started-dev.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/gke-guide.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/index.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/kubernetes-best-practices.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/kubernetes-cluster-requirements.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/kubernetes-deploy.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/kubernetes-production-deployment.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/local-guide.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/production-workflow.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/shared/guides/_deploy-console.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/shared/guides/_deploy-redpanda.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/shared/guides/_explore-topics.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/shared/guides/_next-steps.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/shared/guides/_operator-note.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/shared/guides/_start-streaming.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/shared/guides/_suggested-reading.mdx
  docs/deploy/index.mdx
  sidebars.js
Labels: kubernetes

#1181 Fix external ports
  docs/get-started/quick-start/quick-start-docker.mdx
  versioned_docs/version-22.3/get-started/quick-start/quick-start-docker.mdx
Labels: bug

#1019 docs: Improve doc about TLS
  docs/deploy/deployment-option/self-hosted/kubernetes/kubernetes-cluster-requirements.mdx
  docs/deploy/deployment-option/self-hosted/manual/production/production-deployment.mdx
  docs/manage/kubernetes/configure-storage.mdx
  docs/manage/kubernetes/kubernetes-rack-awareness.mdx
  docs/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
  docs/manage/kubernetes/networking/configure-external-access-nodeport.mdx
  docs/manage/kubernetes/networking/configure-listeners.mdx
  docs/manage/kubernetes/networking/networking-and-connectivity.mdx
  docs/manage/kubernetes/security/index.mdx
  docs/manage/kubernetes/security/kubernetes-tls.mdx
  docs/manage/kubernetes/security/sasl-kubernetes.mdx
  docs/manage/kubernetes/shared/_values-yaml.mdx
  versioned_docs/version-22.2/security/kubernetes-tls.mdx
  versioned_docs/version-22.3/deploy/deployment-option/self-hosted/kubernetes/kubernetes-cluster-requirements.mdx
  versioned_docs/version-22.3/deploy/deployment-option/self-hosted/manual/production/production-deployment.mdx
  versioned_docs/version-22.3/manage/kubernetes/configure-storage.mdx
  versioned_docs/version-22.3/manage/kubernetes/kubernetes-rack-awareness.mdx
  versioned_docs/version-22.3/manage/kubernetes/networking/configure-external-access-loadbalancer.mdx
  versioned_docs/version-22.3/manage/kubernetes/networking/configure-external-access-nodeport.mdx
  versioned_docs/version-22.3/manage/kubernetes/networking/configure-listeners.mdx
  versioned_docs/version-22.3/manage/kubernetes/networking/networking-and-connectivity.mdx
  versioned_docs/version-22.3/manage/kubernetes/security/kubernetes-tls.mdx
  versioned_docs/version-22.3/manage/kubernetes/security/sasl-kubernetes.mdx
  versioned_docs/version-22.3/manage/kubernetes/shared/_values-yaml.mdx
Labels: kubernetes

#1173 cluster_config: Kerberos support
  docs/reference/cluster-properties.mdx
Labels: Q1 23.1 Feature

#1069 docs: rename vectorizedio to redpanda
  docs/labs/data-transform.mdx
  docs/labs/install-preview.mdx
  docs/manage/monitoring.mdx
  docs/reference/internal-metrics.mdx
  docs/reference/redpanda-operator/kubernetes-qs-cloud.mdx
  docs/reference/redpanda-operator/kubernetes-qs-local-access.mdx
  docs/reference/redpanda-operator/kubernetes-qs-minikube.mdx
  versioned_docs/version-21.11/cluster-administration/version-upgrade.mdx
  versioned_docs/version-21.11/data-management/data-migration.mdx
  versioned_docs/version-21.11/data-management/data-transform.mdx
  versioned_docs/version-21.11/deployment/install-preview.mdx
  versioned_docs/version-21.11/quickstart/kubernetes-qs-cloud.mdx
  versioned_docs/version-21.11/quickstart/kubernetes-qs-local-access.mdx
  versioned_docs/version-21.11/quickstart/kubernetes-qs-minikube.mdx
  versioned_docs/version-21.11/quickstart/quick-start-kubernetes.mdx
  versioned_docs/version-22.1/cluster-administration/version-upgrade.mdx
  versioned_docs/version-22.1/data-management/data-migration.mdx
  versioned_docs/version-22.1/data-management/data-transform.mdx
  versioned_docs/version-22.1/deployment/install-preview.mdx
  versioned_docs/version-22.1/quickstart/kubernetes-qs-cloud.mdx
  versioned_docs/version-22.1/quickstart/kubernetes-qs-local-access.mdx
  versioned_docs/version-22.1/quickstart/kubernetes-qs-minikube.mdx
  versioned_docs/version-22.2/data-management/data-migration.mdx
  versioned_docs/version-22.2/install-upgrade/version-upgrade.mdx
  versioned_docs/version-22.2/labs/data-transform.mdx
  versioned_docs/version-22.2/labs/index.mdx
  versioned_docs/version-22.2/labs/install-preview.mdx
  versioned_docs/version-22.2/reference/redpanda-operator/kubernetes-qs-cloud.mdx
  versioned_docs/version-22.2/reference/redpanda-operator/kubernetes-qs-local-access.mdx
  versioned_docs/version-22.2/reference/redpanda-operator/kubernetes-qs-minikube.mdx
  versioned_docs/version-22.3/labs/data-transform.mdx
  versioned_docs/version-22.3/labs/install-preview.mdx
  versioned_docs/version-22.3/reference/redpanda-operator/kubernetes-qs-cloud.mdx
  versioned_docs/version-22.3/reference/redpanda-operator/kubernetes-qs-local-access.mdx
  versioned_docs/version-22.3/reference/redpanda-operator/kubernetes-qs-minikube.mdx
Labels: usability improvement, P3

#1289 engine: Create a context switcher
  docs/manage/data-archiving-index.mdx
  docs/manage/data-archiving.mdx
  docs/manage/kubernetes/data-archiving.mdx
  docs/manage/kubernetes/kubernetes-rack-awareness.mdx
  docs/manage/kubernetes/remote-read-replicas.mdx
  docs/manage/kubernetes/tiered-storage.mdx
  docs/manage/rack-awareness.mdx
  docs/manage/remote-read-replicas-index.mdx
  docs/manage/remote-read-replicas.mdx
  docs/manage/shared/tiered-storage/_cluster-props.mdx
  docs/manage/shared/tiered-storage/_node-props.mdx
  docs/manage/shared/tiered-storage/_remote-write.mdx
  docs/manage/shared/tiered-storage/_tunable-cluster-props.mdx
  docs/manage/tiered-storage-index.mdx
  docs/manage/tiered-storage.mdx
  sidebars.js
  src/components/ContextButton.js
  src/components/ContextButton.module.css
  versioned_docs/version-22.3/manage/data-archiving-index.mdx
  versioned_docs/version-22.3/manage/data-archiving.mdx
  versioned_docs/version-22.3/manage/kubernetes/data-archiving.mdx
  versioned_docs/version-22.3/manage/kubernetes/kubernetes-rack-awareness.mdx
  versioned_docs/version-22.3/manage/kubernetes/remote-read-replicas.mdx
  versioned_docs/version-22.3/manage/kubernetes/tiered-storage.mdx
  versioned_docs/version-22.3/manage/rack-awareness.mdx
  versioned_docs/version-22.3/manage/remote-read-replicas-index.mdx
  versioned_docs/version-22.3/manage/remote-read-replicas.mdx
  versioned_docs/version-22.3/manage/shared/tiered-storage/_cluster-props.mdx
  versioned_docs/version-22.3/manage/shared/tiered-storage/_node-props.mdx
  versioned_docs/version-22.3/manage/shared/tiered-storage/_remote-write.mdx
  versioned_docs/version-22.3/manage/shared/tiered-storage/_tunable-cluster-props.mdx
  versioned_docs/version-22.3/manage/tiered-storage-index.mdx
  versioned_docs/version-22.3/manage/tiered-storage.mdx
  versioned_sidebars/version-22.3-sidebars.json
Labels: website engine, usability improvement

#1281 docs: Improve Kubernetes guides with more details
  docs/deploy/deployment-option/self-hosted/kubernetes/eks-guide.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/get-started-dev.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/kubernetes-cluster-requirements.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/shared/_default-components.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/shared/guides/_external-access-intro.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/shared/guides/_next-steps.mdx
  docs/deploy/deployment-option/self-hosted/kubernetes/shared/guides/_operator-note.mdx
  docs/get-started/quick-start.mdx
  docs/manage/kubernetes/networking/configure-listeners.mdx
  docs/manage/kubernetes/networking/networking-and-connectivity.mdx
  docs/manage/kubernetes/shared/_listener-nodeports.mdx
  versioned_docs/version-22.3/deploy/deployment-option/self-hosted/kubernetes/get-started-dev.mdx
  versioned_docs/version-22.3/deploy/deployment-option/self-hosted/kubernetes/kubernetes-cluster-requirements.mdx
  versioned_docs/version-22.3/deploy/deployment-option/self-hosted/kubernetes/shared/_default-components.mdx
  versioned_docs/version-22.3/deploy/deployment-option/self-hosted/kubernetes/shared/guides/_operator-note.mdx
  versioned_docs/version-22.3/get-started/quick-start.mdx
  versioned_docs/version-22.3/manage/kubernetes/networking/configure-listeners.mdx
  versioned_docs/version-22.3/manage/kubernetes/networking/networking-and-connectivity.mdx
  versioned_docs/version-22.3/manage/kubernetes/shared/_listener-nodeports.mdx
Labels: kubernetes
